In [1]:
%load_ext autoreload
%autoreload 2

import warnings
warnings.filterwarnings('ignore')

# Função 3

In [2]:
from sympy import symbols

variaveis = list(symbols('x_1 x_2'))

print("Variáveis da função 3:")
display(variaveis)

Variáveis da função 3:


[x_1, x_2]

In [3]:
x_1, x_2 = variaveis

f_x = (x_1**2 + x_2 - 11)**2 + (x_1 + x_2**2 - 7)**2

print("Função 3:")
display(f_x)

Função 3:


(x_1 + x_2**2 - 7)**2 + (x_1**2 + x_2 - 11)**2

In [4]:
from algoritmos import calcula_gradiente

grad_f_x = calcula_gradiente(f_x, variaveis)

print("Vetor gradiente da função 3:")
display(grad_f_x)

Vetor gradiente da função 3:


[4*x_1*(x_1**2 + x_2 - 11) + 2*x_1 + 2*x_2**2 - 14,
 2*x_1**2 + 4*x_2*(x_1 + x_2**2 - 7) + 2*x_2 - 22]

In [5]:
from algoritmos import calcula_hessiana

hess_f_x = calcula_hessiana(f_x, variaveis)

print("Matriz Hessiana da função 3:")
display(hess_f_x)

Matriz Hessiana da função 3:


Matrix([
[12*x_1**2 + 4*x_2 - 42,          4*x_1 + 4*x_2],
[         4*x_1 + 4*x_2, 4*x_1 + 12*x_2**2 - 26]])

In [6]:
# TODO: Estudo da função: pontos críticos, convexidade, existência de ponto(s) ótimo(s), além de plotar sua função, etc.

In [7]:
# TODO: Achar os melhores valores de gama e eta

In [8]:
import numpy as np
import pandas as pd

colunas = ['Ponto inicial', '# de iteracoes', '# de cham. de armijo', 'Ponto otimo', 'Valor otimo', 'Erro de aproximação']

pontos = [
  np.array([2.9, 2.1]), 
  np.array([-3.1, -1.9]), 
  # np.array([30, 20]), 
  np.array([4, -2]), 
  np.array([-3, 1]), 
  np.array([2.5, 1.5]), 
  np.array([-3.5, 2.5]), 
  # np.array([0, 0]), 
  np.array([5, 5]), 
  np.array([3.9, -0.9])
  ]

eta = 0.02
gama = 0.08

df_base = pd.DataFrame(columns=colunas)

print("Gama:", gama)
print("Eta:", eta)

print("Pontos a serem testados:")
display(pontos)

Gama: 0.08
Eta: 0.02
Pontos a serem testados:


[array([2.9, 2.1]),
 array([-3.1, -1.9]),
 array([ 4, -2]),
 array([-3,  1]),
 array([2.5, 1.5]),
 array([-3.5,  2.5]),
 array([5, 5]),
 array([ 3.9, -0.9])]

### Gradiente

In [9]:
from algoritmos import metodo_do_gradiente
from utils import substitui_variaveis_funcao, substitui_variaveis_gradiente

df_gradiente = df_base.copy()

for ponto in pontos:
    ponto_otimo, n_iteracoes, n_iteracoes_armijo = metodo_do_gradiente(f_x, grad_f_x, variaveis, ponto, gama, eta)
    valor_otimo = substitui_variaveis_funcao(f_x, variaveis, ponto_otimo)
    erro_aproximacao = np.linalg.norm(substitui_variaveis_gradiente(grad_f_x, variaveis, ponto_otimo))
    df_gradiente = pd.concat([df_gradiente, pd.DataFrame([[ponto, n_iteracoes, n_iteracoes_armijo, ponto_otimo, valor_otimo, erro_aproximacao]], columns=colunas)])

df_gradiente

Ponto inicial # de iteracoes # de cham. de armijo  \
0    [2.9, 2.1]             84                  252   
0  [-3.1, -1.9]             34                  102   
0       [4, -2]             76                  228   
0       [-3, 1]             33                   98   
0    [2.5, 1.5]             90                  270   
0   [-3.5, 2.5]             32                   96   
0        [5, 5]             87                  261   
0   [3.9, -0.9]             75                  224   

                                 Ponto otimo           Valor otimo  \
0    [2.9999999871723535, 2.000000030968677]  1.44471927006780e-14   
0  [-3.779310249141585, -3.2831859844556535]  2.28410967597959e-15   
0   [3.584428343210148, -1.8481265585150146]  1.43988967999011e-14   
0      [-2.80511807717992, 3.13131251746568]  3.11637151361090e-15   
0     [3.000000014152871, 1.999999965831946]  1.75864679215918e-14   
0   [-2.805118099385625, 3.1313125191754843]  5.03923646894922e-15   
0    [2.9999999873380863, 2.000000030568562]  1.40762890189073e-14   
0   [3.5844283429731827, -1.848126555918729]  1.21266425546564e-14   

   Erro de aproximação  
0         8.619978e-07  
0         5.683649e-07  
0         9.089710e-07  
0         6.357159e-07  
0         9.510508e-07  
0         8.083988e-07  
0         8.508608e-07  
0         8.341722e-07

### Newton

In [10]:
from algoritmos import metodo_de_newton

df_newton = df_base.copy()

for ponto in pontos:
    ponto_otimo, n_iteracoes, n_iteracoes_armijo = metodo_de_newton(f_x, grad_f_x, hess_f_x, variaveis, ponto, gama, eta)
    valor_otimo = substitui_variaveis_funcao(f_x, variaveis, ponto_otimo)
    erro_aproximacao = np.linalg.norm(substitui_variaveis_gradiente(grad_f_x, variaveis, ponto_otimo))
    df_newton = pd.concat([df_newton, pd.DataFrame([[ponto, n_iteracoes, n_iteracoes_armijo, ponto_otimo, valor_otimo, erro_aproximacao]], columns=colunas)])

display(df_newton)

Ponto inicial # de iteracoes # de cham. de armijo  \
0    [2.9, 2.1]              3                    3   
0  [-3.1, -1.9]           1000                18000   
0       [4, -2]              4                    4   
0       [-3, 1]           1000                16000   
0    [2.5, 1.5]              6                    6   
0   [-3.5, 2.5]              5                    5   
0        [5, 5]              7                    7   
0   [3.9, -0.9]           1000                16999   

                                 Ponto otimo           Valor otimo  \
0    [2.999999999994683, 2.0000000000905223]  1.30722920078871e-19   
0                               [-3.1, -1.9]      52.9442000000000   
0  [3.5844283403306787, -1.8481265269646487]  2.39697947295449e-24   
0                                [-3.0, 1.0]      82.0000000000000   
0   [2.9999999999999996, 2.0000000000000013]  2.85962078142617e-29   
0  [-2.8051180869526786, 3.1313125182519217]  7.34582642591770e-23   
0     [2.999999999999999, 2.000000000000003]  1.38247873639982e-28   
0                 [3.9, -0.8999999999999998]      16.2002000000000   

   Erro de aproximação  
0         3.291991e-09  
0         5.099784e+01  
0         1.883973e-11  
0         3.847077e+01  
0         4.234479e-14  
0         1.087644e-10  
0         8.800141e-14  
0         4.934780e+01

### Quase-Newton

In [11]:
from algoritmos import metodo_de_quase_newton

df_quase_newton = df_base.copy()

for metodo in ['bfgs', 'dfp']:
    for ponto in pontos:
        ponto_otimo, n_iteracoes, n_iteracoes_armijo = metodo_de_quase_newton(f_x, len(variaveis), grad_f_x, variaveis, ponto, gama, eta, metodo=metodo)
        valor_otimo = substitui_variaveis_funcao(f_x, variaveis, ponto_otimo)
        erro_aproximacao = np.linalg.norm(substitui_variaveis_gradiente(grad_f_x, variaveis, ponto_otimo))
        df_quase_newton = pd.concat([df_quase_newton, pd.DataFrame([[ponto, n_iteracoes, n_iteracoes_armijo, ponto_otimo, valor_otimo, erro_aproximacao]], columns=colunas)])

display(df_quase_newton)

Ponto inicial # de iteracoes # de cham. de armijo  \
0    [2.9, 2.1]              6                   10   
0  [-3.1, -1.9]             10                   14   
0       [4, -2]              8                   12   
0       [-3, 1]             11                   15   
0    [2.5, 1.5]             11                   15   
0   [-3.5, 2.5]              8                   12   
0        [5, 5]             12                   16   
0   [3.9, -0.9]              8                   11   
0    [2.9, 2.1]            970                 1036   
0  [-3.1, -1.9]            142                  225   
0       [4, -2]            170                  199   
0       [-3, 1]            249                  340   
0    [2.5, 1.5]             97                  181   
0   [-3.5, 2.5]            172                  268   
0        [5, 5]            225                  275   
0   [3.9, -0.9]           1000                 1038   

                                  Ponto otimo           Valor otimo  \
0     [3.000000004248617, 2.0000000074988074]  2.26101481887892e-15   
0     [-3.779310253872054, -3.28318598886467]  3.06706819568413e-16   
0   [3.5844283392143734, -1.8481265250314056]  1.05067791191503e-16   
0    [-2.8051180868471293, 3.131312518190818]  4.97622791067289e-19   
0     [2.999999999666529, 1.9999999998905473]  5.04815226265993e-18   
0    [-2.805118086714211, 3.1313125185906223]  6.60443181136824e-18   
0     [3.0000000011406276, 2.000000000028528]  4.88027994940044e-17   
0   [3.5844283406243678, -1.8481265271285792]  4.58489646148835e-18   
0    [2.9999999901548584, 2.0000000350780045]  1.75972627719875e-14   
0  [-3.7793102629648425, -3.2831859966231716]  5.15428911527457e-15   
0   [3.5844283409836337, -1.8481265570602603]  1.31663510180141e-14   
0    [-2.805118072454925, 3.1313125204554795]  7.06300849098380e-15   
0    [2.9999999933546193, 1.9999999896576925]  4.82690798169418e-15   
0       [-2.8051180999568, 3.131312514490294]  6.12416481584041e-15   
0      [3.000000005422473, 1.999999974105195]  9.67883677643458e-15   
0   [3.5844298011361695, -1.8481290189090889]  1.77570750863878e-10   

   Erro de aproximação  
0         5.754969e-07  
0         2.601114e-07  
0         1.145091e-07  
0         8.233499e-09  
0         2.880532e-08  
0         3.192689e-08  
0         8.824228e-08  
0         2.978298e-08  
0         9.961148e-07  
0         9.844237e-07  
0         8.891954e-07  
0         9.646825e-07  
0         8.501958e-07  
0         9.075900e-07  
0         7.807349e-07  
0         1.496392e-04