In [1]:
%load_ext autoreload
%autoreload 2

import warnings
warnings.filterwarnings('ignore')

# Função 2

In [2]:
from sympy import symbols

variaveis = list(symbols('x1:101'))

print("Variáveis da função 2:")
display(variaveis)

Variáveis da função 2:


[x1,
 x2,
 x3,
 x4,
 x5,
 x6,
 x7,
 x8,
 x9,
 x10,
 x11,
 x12,
 x13,
 x14,
 x15,
 x16,
 x17,
 x18,
 x19,
 x20,
 x21,
 x22,
 x23,
 x24,
 x25,
 x26,
 x27,
 x28,
 x29,
 x30,
 x31,
 x32,
 x33,
 x34,
 x35,
 x36,
 x37,
 x38,
 x39,
 x40,
 x41,
 x42,
 x43,
 x44,
 x45,
 x46,
 x47,
 x48,
 x49,
 x50,
 x51,
 x52,
 x53,
 x54,
 x55,
 x56,
 x57,
 x58,
 x59,
 x60,
 x61,
 x62,
 x63,
 x64,
 x65,
 x66,
 x67,
 x68,
 x69,
 x70,
 x71,
 x72,
 x73,
 x74,
 x75,
 x76,
 x77,
 x78,
 x79,
 x80,
 x81,
 x82,
 x83,
 x84,
 x85,
 x86,
 x87,
 x88,
 x89,
 x90,
 x91,
 x92,
 x93,
 x94,
 x95,
 x96,
 x97,
 x98,
 x99,
 x100]

In [3]:
f_x = sum([xi**4 - 16*xi**2 + 5*xi for xi in variaveis])

print("Função 2:")
display(f_x)

Função 2:


x1**4 - 16*x1**2 + 5*x1 + x10**4 - 16*x10**2 + 5*x10 + x100**4 - 16*x100**2 + 5*x100 + x11**4 - 16*x11**2 + 5*x11 + x12**4 - 16*x12**2 + 5*x12 + x13**4 - 16*x13**2 + 5*x13 + x14**4 - 16*x14**2 + 5*x14 + x15**4 - 16*x15**2 + 5*x15 + x16**4 - 16*x16**2 + 5*x16 + x17**4 - 16*x17**2 + 5*x17 + x18**4 - 16*x18**2 + 5*x18 + x19**4 - 16*x19**2 + 5*x19 + x2**4 - 16*x2**2 + 5*x2 + x20**4 - 16*x20**2 + 5*x20 + x21**4 - 16*x21**2 + 5*x21 + x22**4 - 16*x22**2 + 5*x22 + x23**4 - 16*x23**2 + 5*x23 + x24**4 - 16*x24**2 + 5*x24 + x25**4 - 16*x25**2 + 5*x25 + x26**4 - 16*x26**2 + 5*x26 + x27**4 - 16*x27**2 + 5*x27 + x28**4 - 16*x28**2 + 5*x28 + x29**4 - 16*x29**2 + 5*x29 + x3**4 - 16*x3**2 + 5*x3 + x30**4 - 16*x30**2 + 5*x30 + x31**4 - 16*x31**2 + 5*x31 + x32**4 - 16*x32**2 + 5*x32 + x33**4 - 16*x33**2 + 5*x33 + x34**4 - 16*x34**2 + 5*x34 + x35**4 - 16*x35**2 + 5*x35 + x36**4 - 16*x36**2 + 5*x36 + x37**4 - 16*x37**2 + 5*x37 + x38**4 - 16*x38**2 + 5*x38 + x39**4 - 16*x39**2 + 5*x39 + x4**4 - 16*x4**2 + 5

In [5]:
from algoritmos import calcula_gradiente

grad_f_x = calcula_gradiente(f_x, variaveis)

print("Vetor gradiente da função 2:")
display(grad_f_x)

Vetor gradiente da função 2:


[4*x1**3 - 32*x1 + 5,
 4*x2**3 - 32*x2 + 5,
 4*x3**3 - 32*x3 + 5,
 4*x4**3 - 32*x4 + 5,
 4*x5**3 - 32*x5 + 5,
 4*x6**3 - 32*x6 + 5,
 4*x7**3 - 32*x7 + 5,
 4*x8**3 - 32*x8 + 5,
 4*x9**3 - 32*x9 + 5,
 4*x10**3 - 32*x10 + 5,
 4*x11**3 - 32*x11 + 5,
 4*x12**3 - 32*x12 + 5,
 4*x13**3 - 32*x13 + 5,
 4*x14**3 - 32*x14 + 5,
 4*x15**3 - 32*x15 + 5,
 4*x16**3 - 32*x16 + 5,
 4*x17**3 - 32*x17 + 5,
 4*x18**3 - 32*x18 + 5,
 4*x19**3 - 32*x19 + 5,
 4*x20**3 - 32*x20 + 5,
 4*x21**3 - 32*x21 + 5,
 4*x22**3 - 32*x22 + 5,
 4*x23**3 - 32*x23 + 5,
 4*x24**3 - 32*x24 + 5,
 4*x25**3 - 32*x25 + 5,
 4*x26**3 - 32*x26 + 5,
 4*x27**3 - 32*x27 + 5,
 4*x28**3 - 32*x28 + 5,
 4*x29**3 - 32*x29 + 5,
 4*x30**3 - 32*x30 + 5,
 4*x31**3 - 32*x31 + 5,
 4*x32**3 - 32*x32 + 5,
 4*x33**3 - 32*x33 + 5,
 4*x34**3 - 32*x34 + 5,
 4*x35**3 - 32*x35 + 5,
 4*x36**3 - 32*x36 + 5,
 4*x37**3 - 32*x37 + 5,
 4*x38**3 - 32*x38 + 5,
 4*x39**3 - 32*x39 + 5,
 4*x40**3 - 32*x40 + 5,
 4*x41**3 - 32*x41 + 5,
 4*x42**3 - 32*x42 + 5,
 4*x43**3 

In [8]:
from algoritmos import calcula_hessiana

hess_f_x = calcula_hessiana(f_x, variaveis)

print("Matriz Hessiana da função 2:")
display(hess_f_x)

Matriz Hessiana da função 2:


Matrix([
[12*x1**2 - 32,             0,             0,             0,             0,             0,             0,             0,             0,              0,              0,              0,              0,              0,              0,              0,              0,              0,              0,              0,              0,              0,              0,              0,              0,              0,              0,              0,              0,              0,              0,              0,              0,              0,              0,              0,              0,              0,              0,              0,              0,              0,              0,              0,              0,              0,              0,              0,              0,              0,              0,              0,              0,              0,              0,              0,              0,              0,              0,              0,              0,              0,        

In [ ]:
# TODO: Estudo da função: pontos críticos, convexidade, existência de ponto(s) ótimo(s), além de plotar sua função, etc.

In [ ]:
# TODO: Achar os melhores valores de gama e eta

In [10]:
import numpy as np
import pandas as pd

colunas = ['Algoritmo', 'Ponto inicial', '# de iteracoes', '# de cham. de armijo', 'Ponto otimo', 'Valor otimo', 'Erro de aproximação']

pontos = [
  np.array([2.9, 2.1]), 
  np.array([-3.1, -1.9]), 
  # np.array([30, 20]), 
  np.array([4, -2]), 
  np.array([-3, 1]), 
  np.array([2.5, 1.5]), 
  np.array([-3.5, 2.5]), 
  # np.array([0, 0]), 
  np.array([5, 5]), 
  np.array([3.9, -0.9])
  ]

eta = 0.02
gama = 0.08

df_base = pd.DataFrame(columns=colunas)

print("Gama:", gama)
print("Eta:", eta)

print("Pontos a serem testados:")
display(pontos)

Gama: 0.08
Eta: 0.02
Pontos a serem testados:


[array([2.9, 2.1]),
 array([-3.1, -1.9]),
 array([ 4, -2]),
 array([-3,  1]),
 array([2.5, 1.5]),
 array([-3.5,  2.5]),
 array([5, 5]),
 array([ 3.9, -0.9])]

### Gradiente

In [13]:
from algoritmos import metodo_do_gradiente
from utils import substitui_variaveis_funcao, substitui_variaveis_gradiente

df_gradiente = df_base.copy()

for ponto in pontos:
    ponto_otimo, n_iteracoes, n_iteracoes_armijo = metodo_do_gradiente(f_x, grad_f_x, variaveis, ponto, gama, eta)
    valor_otimo = substitui_variaveis_funcao(f_x, variaveis, ponto_otimo)
    erro_aproximacao = np.linalg.norm(substitui_variaveis_gradiente(grad_f_x, variaveis, ponto_otimo))
    df_gradiente = pd.concat([df_gradiente, pd.DataFrame([['gradiente', ponto, n_iteracoes, n_iteracoes_armijo, ponto_otimo, valor_otimo, erro_aproximacao]], columns=colunas)])

df_gradiente

TypeError: Cannot convert expression to float

### Newton

In [14]:
from algoritmos import metodo_de_newton

df_newton = df_base.copy()

for ponto in pontos:
    ponto_otimo, n_iteracoes, n_iteracoes_armijo = metodo_de_newton(f_x, grad_f_x, hess_f_x, variaveis, ponto, gama, eta)
    valor_otimo = substitui_variaveis_funcao(f_x, variaveis, ponto_otimo)
    erro_aproximacao = np.linalg.norm(substitui_variaveis_gradiente(grad_f_x, variaveis, ponto_otimo))
    df_newton = pd.concat([df_newton, pd.DataFrame([['newton', ponto, n_iteracoes, n_iteracoes_armijo, ponto_otimo, valor_otimo, erro_aproximacao]], columns=colunas)])

display(df_newton)

TypeError: Cannot convert expression to float

### Quase-Newton

In [15]:
from algoritmos import metodo_de_quase_newton

df_quase_newton = df_base.copy()

for metodo in ['bfgs', 'dfp']:
    for ponto in pontos:
        ponto_otimo, n_iteracoes, n_iteracoes_armijo = metodo_de_quase_newton(f_x, len(variaveis), grad_f_x, variaveis, ponto, gama, eta, metodo=metodo)
        valor_otimo = substitui_variaveis_funcao(f_x, variaveis, ponto_otimo)
        erro_aproximacao = np.linalg.norm(substitui_variaveis_gradiente(grad_f_x, variaveis, ponto_otimo))
        df_quase_newton = pd.concat([df_quase_newton, pd.DataFrame([[f'quase-newtown ({metodo})', ponto, n_iteracoes, n_iteracoes_armijo, ponto_otimo, valor_otimo, erro_aproximacao]], columns=colunas)])

display(df_quase_newton)

TypeError: Cannot convert expression to float

## Tabela geral

In [16]:
df_all = pd.concat([df_gradiente, df_newton, df_quase_newton])
df_all

Empty DataFrame
Columns: [Algoritmo, Ponto inicial, # de iteracoes, # de cham. de armijo, Ponto otimo, Valor otimo, Erro de aproximação]
Index: []